### ISSUE TITLE
ballerina: unable to create the file system cache of Ballerina Central 

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-update-tool#147]
Reported by Kirill Keker on slack

When you install Ballerina on MacOS, the Root user password is asked during installation to create the /Library/Ballerina folder - this is normal.

Then, when executing the bal update or bal dist update commands, sudo access is also requested because these commands want to get the entry in /Library/Ballerina that belongs to Root.

If after that you did not have the ~/.ballerina folder or you deleted it, then it will be created as root in your folder and you will not have write access. The same will happen if you run sudo bal dist use.In order not to start your rights, if there is only one user on the PC (like mine), then it is better to execute sudo chown -R $USER /Library/Ballerina after installing Ballerina - this command will correct the rights on the user and there will be no more confusion with the rights, no longer have to use sudo and think about which folder belongs to whom.

**Comment by DamithaSenevirathne** [comment]
Similar permission issue occurred when building Ballerina from the source code after installing Ballerina following Linux instructions (Ubuntu 20.04.2 LTS). During the Linux installation process root access is required and due to this reason /home/./ballerina folder needs root access to access the file. Because of this reason permission error occurs when building from the source code. After removing the /home/./ballerina folder build was successful.
